(require '[eta-mu.receipt-river.api :as rr] '[eta-mu.receipt-river.shape.edn :as edn] '[clojure.string :as str] '["node:fs" :as fs] '["node:crypto" :as crypto])
(def target "/tmp/foresight-chat-ui-abort-planning-8px3s7dh/worktree/.ημ/receipts.edn")
(def old (fs/readFileSync target "utf8"))
(def rows (str/split-lines old))
(assert (= 3 (count rows)))
(def prior-hash (.digest (.update (.createHash crypto "sha256") old) "hex"))
(def prior (:event (rr/validate-line (first rows) 1)))
(def ts (.toISOString (js/Date.)))
(def event (rr/build-event {:event-id (uuid "8c0dde2a-2b89-4eb4-acfb-8ba8d9a47f74") :recorded-at ts :component-manifest {:eta-mu/version "1.1.1"} :command "authorized-upstream-chat-ui-bug-issue-publication" :subject {:repo "open-hax/chat-ui" :issue 1 :source-checkpoint "8d3cd175cbb99a5a25def37ab1ea0d5395d5942e"}}
 (assoc (:event/payload prior) :ts ts :kind :push-truth :manifest ["docs/agile/tasks/chat-ui-opencode-abort-state.md" "docs/notes/chat-ui-opencode-abort-state-plan.md" ".ημ/verification/chat-ui-abort-planning/issue-publication"] :refs ["https://github.com/open-hax/chat-ui/issues/1" "8d3cd175cbb99a5a25def37ab1ea0d5395d5942e" prior-hash] :note (str "Root independently reproduced and reviewed8d3. One authorized upstream bug issue1 published with exact6criteria after fresh all-state duplicate/head guards, riatzukiza MEMBER readback exact; bodySHA f3b56aa1ad24ffb29ca293d89aee7c5514a553f07565c473f685acebe2982522. Prior3rows exact prefixSHA=" prior-hash ". Incoming card and design get append-only source links. No cold-contractissue, PR, push, implementation, reviewer or board transition. Root final successor peer required.") :tests "Native issue/body/member readback exact. OwningRR154440 validates new :push-truth and all4owned declared-schema rows. Checkpoint source/captures/artifacts preserved; new nativeRheos incoming readback and base/fulltip diff hygiene verified separately.")))
(def line (edn/format-line event))
(assert (:ok (rr/validate-line line 4)))
(fs/appendFileSync target (str line "\n"))
(println (pr-str {:ok true :kind :push-truth :prior3sha256 prior-hash :id "8c0dde2a-2b89-4eb4-acfb-8ba8d9a47f74"}))
